//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaManageSystemEntities : DbContext
    {
        public CinemaManageSystemEntities()
            : base("name=CinemaManageSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<CityInfo> CityInfoes { get; set; }
        public virtual DbSet<FilmInfor> FilmInfors { get; set; }
        public virtual DbSet<FilmOnInfor> FilmOnInfors { get; set; }
        public virtual DbSet<HallInfo> HallInfoes { get; set; }
        public virtual DbSet<MemberInfor> MemberInfors { get; set; }
        public virtual DbSet<MovieInfo> MovieInfoes { get; set; }
        public virtual DbSet<MovieType> MovieTypes { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<refund> refunds { get; set; }
        public virtual DbSet<SeatInfor> SeatInfors { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketAffair> TicketAffairs { get; set; }
        public virtual DbSet<WantSee> WantSees { get; set; }
        public virtual DbSet<character> characters { get; set; }
        public virtual DbSet<Year> Years { get; set; }
    }
}
