//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HallInfo
    {
        public int theaterid { get; set; }
        public string theatername { get; set; }
        public int cityid { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public string hours { get; set; }
        public string seatnum { get; set; }
        public string roomnum { get; set; }
        public string logo { get; set; }
        public string score { get; set; }
        public string summary { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string city { get; set; }
    
        public virtual CityInfo CityInfo { get; set; }
    }
}
