//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberInfor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberInfor()
        {
            this.Tickets = new HashSet<Ticket>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.refunds = new HashSet<refund>();
            this.WantSees = new HashSet<WantSee>();
        }
    
        public int Mno { get; set; }
        public string Mname { get; set; }
        public string Mpassword { get; set; }
        public string Mphone { get; set; }
        public string Memail { get; set; }
        public string Mlevel { get; set; }
        public Nullable<System.DateTime> SendMailTIme { get; set; }
        public Nullable<int> MailActive { get; set; }
        public string img { get; set; }
        public decimal money { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual MemberInfor MemberInfor1 { get; set; }
        public virtual MemberInfor MemberInfor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<refund> refunds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WantSee> WantSees { get; set; }
    }
}
