//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieInfo()
        {
            this.WantSees = new HashSet<WantSee>();
        }
    
        public string moviename { get; set; }
        public int movieid { get; set; }
        public string enname { get; set; }
        public string pic { get; set; }
        public string typeclass { get; set; }
        public Nullable<int> years { get; set; }
        public System.DateTime releasedate { get; set; }
        public string country { get; set; }
        public string director { get; set; }
        public string actor { get; set; }
        public string summary { get; set; }
        public string screentype { get; set; }
        public string duration { get; set; }
        public string language { get; set; }
        public Nullable<int> OnSale { get; set; }
        public Nullable<int> WantSee { get; set; }
        public Nullable<int> other { get; set; }
        public Nullable<decimal> Ticket { get; set; }
        public Nullable<int> Marknum { get; set; }
        public Nullable<int> score { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WantSee> WantSees { get; set; }
    }
}
