//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string Orderid { get; set; }
        public int Userid { get; set; }
        public string moviename { get; set; }
        public string time { get; set; }
        public string cinema { get; set; }
        public string Seat { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public decimal price { get; set; }
        public int state { get; set; }
        public string pic { get; set; }
        public System.DateTime year { get; set; }
        public System.DateTime creattime { get; set; }
        public int PayState { get; set; }
    
        public virtual MemberInfor MemberInfor { get; set; }
    }
}
