//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refund
    {
        public string orderid { get; set; }
        public int uid { get; set; }
        public string moviename { get; set; }
        public string time { get; set; }
        public string cinema { get; set; }
        public string seat { get; set; }
        public decimal price { get; set; }
        public int State { get; set; }
    
        public virtual MemberInfor MemberInfor { get; set; }
    }
}
