//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketAffairs = new HashSet<TicketAffair>();
        }
    
        public int Tno { get; set; }
        public Nullable<int> Fshow { get; set; }
        public Nullable<int> SeatID { get; set; }
        public Nullable<int> Mno { get; set; }
        public string Ttype { get; set; }
        public Nullable<double> Tprice { get; set; }
    
        public virtual FilmOnInfor FilmOnInfor { get; set; }
        public virtual MemberInfor MemberInfor { get; set; }
        public virtual SeatInfor SeatInfor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketAffair> TicketAffairs { get; set; }
    }
}
